### PR TITLE
feat: Add immediate deletion of groups

### PR DESCRIPTION
**Pull request by buehlmann**
### Description of your changes

On GitLab [Premium](https://about.gitlab.com/pricing/premium/) and [Ultimate](https://about.gitlab.com/pricing/ultimate/), the delete action on a group just marks the group as deleted. By default, the group will be deleted seven days in the future.  To delete the group immediately two rest calls are needed:

1. DELETE request to `/groups/:id` which marks the group in the "pending for deletion" state ([docs](https://docs.gitlab.com/ee/api/groups.html#delete-a-group))
2. DELETE request to `/groups/:id` with attributes `permanently_remove=true` and `full_path` set. The group will be deleted immediate.

This change introduce the optional fields `PermanentlyRemove` and `FullPath` on the GitLab group resource. This allows the user to enforce an immediate deletion of GitLab groups.

The same behavior exist by deleting projects (see #121, #149) and could be implemented in the same way as done here for groups. Before this feature can be implemented for projects, one needs to extend the _xanzy/go-gitlab_ client with `DeleteProjectOptions` along the lines of [DeleteGroupOptions](https://github.com/xanzy/go-gitlab/blob/main/groups.go#L617-L623).

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Provider has been built locally and deployed on a AKS cluster. Deletion of GitLab Groups has been successfully end to end tested with and without PermanentlyRemove and FullPath fields set.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by dariozachow** [comment]
can you rebase on main?

**Comment by buehlmann** [comment]
@dariozachow MR rebased on master

**Comment by dariozachow** [comment]
Unfortunately this only works for subgroups. Is there some way we can filter for this error ``permanently_remove` option is only available for subgroups` after trying the full deletion once? Or ignore top level groups at all

**Comment by buehlmann** [comment]
I would just skip the newly introduced deletion statement if the group to delete is on the root level. Determine if it's a root group, I would by testing `group.path == group.full_path`. If this condition is true, the group is on the root level. What do you think?

**Comment by dariozachow** [comment]
sounds good to me

**Comment by buehlmann** [comment]
@dariozachow delete logic adjusted as discussed

**Review by dariozachow — APPROVED** [review]

**Pull request merged**
